[package]
name    = "personad"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[[bin]]
name = "personad"
path = "src/main.rs"

[dependencies]
persona-core.workspace     = true
persona-attestors.workspace = true
persona-grpc.workspace     = true
anyhow.workspace           = true
tokio.workspace            = true
tracing.workspace          = true
tracing-subscriber.workspace = true
rustls.workspace             = true
libc.workspace               = true
serde_json.workspace         = true
