//! SVID signing engine: ephemeral ECDSA P-256 keypair, JWT-SVID and X.509-SVID issuance.

use std::time::{SystemTime, UNIX_EPOCH};

use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64URL;
use base64::Engine as _;
use jsonwebtoken::{encode, Algorithm, EncodingKey, Header};
use p256::ecdsa::{signature::Signer as _, Signature, SigningKey};
use p256::pkcs8::EncodePrivateKey as _;
use rand_core::{OsRng, RngCore as _};
use serde::{Deserialize, Serialize};
use sha2::{Digest as _, Sha256};

use crate::consumer::ConsumerIdentity;
use crate::pseudonym::derive_pseudonymous_id;
use crate::spiffe_id::SpiffeId;

// ── Error type ────────────────────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum SignerError {
    #[error("key generation failed: {0}")]
    KeyGen(String),
    #[error("signing failed: {0}")]
    Sign(String),
    #[error("jwt error: {0}")]
    Jwt(#[from] jsonwebtoken::errors::Error),
    #[error("not implemented: {0}")]
    NotImplemented(String),
}

// ── JWT claims ────────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
struct JwtClaims {
    sub: String,
    aud: Vec<String>,
    exp: u64,
    iat: u64,
    spiffe_id: String,
    persona: serde_json::Value,
}

// ── SvidSigner ────────────────────────────────────────────────────────────────

/// Holds an ephemeral ECDSA P-256 keypair generated at daemon start.
/// The keypair is never persisted; it is discarded when the process exits.
pub struct SvidSigner {
    signing_key: SigningKey,
    /// Uncompressed SEC1 public point, `0x04 || X || Y`. Fixed-size so that the
    /// JWK coordinate split in `public_xy` is infallible by construction
    /// rather than by assertion.
    public_key_sec1: [u8; 65],
    /// PKCS#8 DER bytes kept for jsonwebtoken ES256 signing.
    pkcs8_der: Vec<u8>,
    /// Per-process key material for consumer pseudonyms. Same lifetime rule as
    /// the keypair: never persisted, discarded when the process exits.
    ///
    /// ponytail: pseudonyms are stable for the daemon's lifetime, not across
    ///   restarts | ceiling: a consumer cannot recognise the same user after
    ///   personad restarts, so SPEC-HIA.md's "correlate across sessions" holds
    ///   only within one run | upgrade path: persist these 32 bytes at 0600
    ///   alongside whatever state enrollment (persona-5s4b.103) introduces; the
    ///   derivation below does not change
    pseudonym_ikm: [u8; 32],
}

impl SvidSigner {
    /// Generate a fresh ephemeral keypair.
    ///
    /// Panics if the operating system CSPRNG is unavailable: `SigningKey::random`
    /// resamples internally and has no fallible form in ecdsa 0.16.
    pub fn new() -> Result<Self, SignerError> {
        Self::from_signing_key(SigningKey::random(&mut OsRng))
    }

    /// Load a fixed keypair from PKCS#8 DER, for the known-answer vectors below.
    /// Production keys are ephemeral and generated by `new`.
    #[cfg(test)]
    fn from_pkcs8_der(pkcs8: &[u8]) -> Result<Self, SignerError> {
        use p256::pkcs8::DecodePrivateKey as _;
        let signing_key =
            SigningKey::from_pkcs8_der(pkcs8).map_err(|e| SignerError::KeyGen(e.to_string()))?;
        Self::from_signing_key(signing_key)
    }

    fn from_signing_key(signing_key: SigningKey) -> Result<Self, SignerError> {
        let pkcs8_der = signing_key
            .to_pkcs8_der()
            .map_err(|e| SignerError::KeyGen(e.to_string()))?
            .as_bytes()
            .to_vec();
        // `to_encoded_point(false)` and never `to_sec1_bytes`: the latter is the
        // compressing accessor by contract, and a 33-byte point would silently
        // change the published trust bundle. The `try_into` is what makes
        // "silently" impossible — a point that is not 65 uncompressed bytes
        // fails here, at key setup, rather than producing a malformed JWK at
        // publication time.
        let public_key_sec1: [u8; 65] = signing_key
            .verifying_key()
            .to_encoded_point(false)
            .as_bytes()
            .try_into()
            .map_err(|_| {
                SignerError::KeyGen("public key is not an uncompressed P-256 point".into())
            })?;
        let mut pseudonym_ikm = [0u8; 32];
        OsRng
            .try_fill_bytes(&mut pseudonym_ikm)
            .map_err(|e| SignerError::KeyGen(e.to_string()))?;
        Ok(Self {
            signing_key,
            public_key_sec1,
            pkcs8_der,
            pseudonym_ikm,
        })
    }

    /// The JWKS published as this daemon's JWT authority for its trust domain.
    ///
    /// Exactly one key, because a persona process signs with exactly one
    /// ephemeral keypair. This is the only encoding of the public key a JWKS
    /// consumer can use, and it is what `FetchJWTBundles` puts on the wire.
    pub fn jwks(&self) -> serde_json::Value {
        let (x, y) = self.public_xy();
        serde_json::json!({
            "keys": [{
                "kty": "EC",
                "crv": "P-256",
                "alg": "ES256",
                "use": "sig",
                "kid": jwk_thumbprint(&x, &y),
                "x": x,
                "y": y,
            }]
        })
    }

    /// The `kid` this signer stamps on every token it issues, and the `kid` of
    /// its entry in [`SvidSigner::jwks`].
    ///
    /// The keypair is regenerated at every daemon start, so "which key signed
    /// this" is a question a consumer holding a cached bundle actually has to
    /// answer. The RFC 7638 thumbprint answers it with no stored state.
    pub fn kid(&self) -> String {
        let (x, y) = self.public_xy();
        jwk_thumbprint(&x, &y)
    }

    /// base64url(X), base64url(Y) of the stored uncompressed point.
    fn public_xy(&self) -> (String, String) {
        (
            B64URL.encode(&self.public_key_sec1[1..33]),
            B64URL.encode(&self.public_key_sec1[33..65]),
        )
    }

    /// The SPIFFE ID this consumer is issued for the given root identity.
    ///
    /// The root identity is an input to derivation and never an output: nothing
    /// derived from it beyond its trust domain (which is the URI authority
    /// either way) appears in the result.
    pub fn pseudonymous_id(&self, root: &SpiffeId, consumer: &ConsumerIdentity) -> SpiffeId {
        derive_pseudonymous_id(&self.pseudonym_ikm, root, consumer)
    }

    // ── JWT-SVID ──────────────────────────────────────────────────────────────

    /// Sign a JWT-SVID (ES256).  TTL: 5 minutes.
    ///
    /// * `spiffe_id`   – full SPIFFE URI, e.g. `spiffe://example.org/workload`
    /// * `audiences`   – one or more audience strings
    /// * `persona_ext` – arbitrary persona claims serialised as JSON
    pub fn sign_jwt_svid(
        &self,
        spiffe_id: &str,
        audiences: &[&str],
        persona_ext: serde_json::Value,
    ) -> Result<String, SignerError> {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock before epoch")
            .as_secs();
        let claims = JwtClaims {
            sub: spiffe_id.to_owned(),
            aud: audiences.iter().map(|s| s.to_string()).collect(),
            exp: now + 300, // 5 minutes
            iat: now,
            spiffe_id: spiffe_id.to_owned(),
            persona: persona_ext,
        };
        let key = EncodingKey::from_ec_der(&self.pkcs8_der);
        let mut header = Header::new(Algorithm::ES256);
        // Names the JWKS entry that verifies this token. Without it a consumer
        // holding more than one key can only trial-verify, which is O(n)
        // signature checks and cannot tell "wrong key" from "bad token".
        header.kid = Some(self.kid());
        let token = encode(&header, &claims, &key)?;
        Ok(token)
    }

    // ── X.509-SVID ────────────────────────────────────────────────────────────

    // ponytail: stub X.509 signer | upgrade path: x509-cert builder over the p256 SigningKey
    /// Sign an X.509-SVID with URI SAN = `spiffe_id`.  TTL: 1 hour.
    ///
    /// Currently stubbed: certificate construction is unimplemented (persona-4qm).
    pub fn sign_x509_svid(&self, _spiffe_id: &str) -> Result<Vec<u8>, SignerError> {
        Err(SignerError::NotImplemented("x509_svid".into()))
    }

    // ── Raw signing ──────────────────────────────────────────────────────────

    /// Sign arbitrary bytes with the ephemeral key: ECDSA P-256 over SHA-256,
    /// fixed-width `r || s`, 64 bytes — the encoding ES256 uses. This is the
    /// primitive `sign_jwt_svid` signs through, and the one the known-answer
    /// vector in this module's tests pins.
    pub fn sign_raw(&self, message: &[u8]) -> Result<Vec<u8>, SignerError> {
        let signature: Signature = self
            .signing_key
            .try_sign(message)
            .map_err(|e| SignerError::Sign(e.to_string()))?;
        Ok(signature.to_vec())
    }
}

/// RFC 7638 §3.2 JWK thumbprint of a P-256 public key.
///
/// The canonical form is written out literally rather than serialised from a
/// `serde_json::Value`: RFC 7638 fixes the exact byte sequence — required
/// members only, lexicographic order, no whitespace — while `serde_json::Map`
/// preserves insertion order the moment any crate in the graph turns on its
/// `preserve_order` feature. A thumbprint that changes because of a sibling
/// crate's feature flag is a key rotation nobody asked for. `x` and `y` are
/// base64url, an alphabet with nothing for JSON to escape.
fn jwk_thumbprint(x: &str, y: &str) -> String {
    let canonical = format!(r#"{{"crv":"P-256","kty":"EC","x":"{x}","y":"{y}"}}"#);
    B64URL.encode(Sha256::digest(canonical.as_bytes()).as_slice())
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_generates_keypair() {
        let signer = SvidSigner::new().expect("keypair generation failed");
        assert_eq!(signer.public_key_sec1.len(), 65);
    }

    #[test]
    fn sign_jwt_svid_produces_three_part_token() {
        let signer = SvidSigner::new().unwrap();
        let token = signer
            .sign_jwt_svid(
                "spiffe://example.org/workload",
                &["api.example.org"],
                serde_json::json!({"level": "asserted"}),
            )
            .unwrap();
        // A compact JWS has exactly three dot-separated parts.
        assert_eq!(token.split('.').count(), 3, "expected compact JWS format");
    }

    #[test]
    fn sign_x509_svid_returns_not_implemented() {
        let signer = SvidSigner::new().unwrap();
        match signer.sign_x509_svid("spiffe://example.org/workload") {
            Err(SignerError::NotImplemented(_)) => {}
            other => panic!("expected NotImplemented, got {:?}", other),
        }
    }

    #[test]
    fn sign_raw_produces_signature() {
        let signer = SvidSigner::new().unwrap();
        let msg = b"hello persona";
        let sig = signer.sign_raw(msg).unwrap();
        assert!(!sig.is_empty());
    }

    #[test]
    fn jwt_svid_claims_are_correct() {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};

        let signer = SvidSigner::new().unwrap();
        let spiffe_id = "spiffe://example.org/workload";
        let audience = "api.example.org";
        let persona_val = serde_json::json!({"level": "asserted"});

        let token = signer
            .sign_jwt_svid(spiffe_id, &[audience], persona_val.clone())
            .unwrap();

        let parts: Vec<&str> = token.split('.').collect();
        assert_eq!(parts.len(), 3);

        let payload_json = URL_SAFE_NO_PAD.decode(parts[1]).unwrap();
        let claims: serde_json::Value = serde_json::from_slice(&payload_json).unwrap();

        assert_eq!(claims["sub"].as_str().unwrap(), spiffe_id);
        assert!(
            claims["aud"]
                .as_array()
                .unwrap()
                .iter()
                .any(|v| v.as_str() == Some(audience)),
            "audience not found in aud claim"
        );
        assert!(
            claims["exp"].as_u64().unwrap() > claims["iat"].as_u64().unwrap(),
            "exp must be after iat"
        );
        assert_eq!(claims["spiffe_id"].as_str().unwrap(), spiffe_id);
        assert_eq!(claims["persona"], persona_val);
    }

    // Generated once, offline. Regenerate with:
    //   openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 \
    //     -pkeyopt ec_param_enc:named_curve -outform DER -out k.sec1.der
    //   openssl pkcs8 -topk8 -nocrypt -inform DER -in k.sec1.der -outform DER -out k.pkcs8.der
    const TEST_PKCS8_HEX: &str = "308187020100301306072a8648ce3d020106082a8648ce3d030107046d306b02010104205cc28f43751c40760f2c13143e0001ff32b7aee71161f9114fa09e0d7b361e36a14403420004fe3e909303ea44121e359ecdec67c166bbfae904d90846e8d0b670903e9485e5ccf81d4ab7490092473e3b53c8159665f57faab541bd7ec613853087da07f4fa";
    // pyca/cryptography: public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)
    const TEST_SEC1_HEX: &str = "04fe3e909303ea44121e359ecdec67c166bbfae904d90846e8d0b670903e9485e5ccf81d4ab7490092473e3b53c8159665f57faab541bd7ec613853087da07f4fa";
    // python-ecdsa: sign_deterministic(hashfunc=sha256, sigencode=sigencode_string).
    // Cross-verified by pyca and `openssl dgst -sha256 -verify`.
    const TEST_SIG_HEX: &str = "d34088ca63c7f9733869c7b28a52706bb64ba4d2517a226759ea46d9011a54ef11de38cbf5ba7b4ca67a273997f1973e8755ed275720644039771dcf44c1a3f8";
    const TEST_MSG: &[u8] = b"persona ring-removal known-answer vector v1";
    // pyca/cryptography over TEST_SEC1_HEX: public_numbers().x / .y, 32-byte
    // big-endian, base64url unpadded. Regenerate with:
    //   python3 -c "
    //   import base64
    //   from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurvePublicKey, SECP256R1
    //   n = EllipticCurvePublicKey.from_encoded_point(SECP256R1(), bytes.fromhex(SEC1)).public_numbers()
    //   b = lambda v: base64.urlsafe_b64encode(v.to_bytes(32,'big')).decode().rstrip('=')
    //   print(b(n.x), b(n.y))"
    const TEST_JWK_X: &str = "_j6QkwPqRBIeNZ7N7GfBZrv66QTZCEbo0LZwkD6UheU";
    const TEST_JWK_Y: &str = "zPgdSrdJAJJHPjtTyBWWZfV_qrVBvX7GE4Uwh9oH9Po";
    // RFC 7638 §3.2 thumbprint of that JWK: SHA-256 over
    // {"crv":"P-256","kty":"EC","x":"...","y":"..."}, base64url unpadded.
    // Regenerate with python3 json+hashlib, sort_keys=True, separators=(',',':').
    const TEST_JWK_KID: &str = "fdGIPrvovavwHlqBF_eSYE7EpaCnB7m3IPAOaQAgdT8";

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    fn unhex(s: &str) -> Vec<u8> {
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("test vector is not hex"))
            .collect()
    }

    fn fixed_key_signer() -> SvidSigner {
        SvidSigner::from_pkcs8_der(&unhex(TEST_PKCS8_HEX)).expect("fixture key rejected")
    }

    #[test]
    fn known_vector_public_key_and_pkcs8() {
        let signer = fixed_key_signer();
        // 65-byte uncompressed SEC1 point. SPKI (91 bytes) or a compressed
        // point (33) would fail here, which is the point of the assertion.
        assert_eq!(hex(&signer.public_key_sec1), TEST_SEC1_HEX);
        assert_eq!(hex(&signer.pkcs8_der), TEST_PKCS8_HEX);
    }

    #[test]
    fn known_vector_sign_raw() {
        let signer = fixed_key_signer();
        let sig = signer.sign_raw(TEST_MSG).expect("signing failed");
        assert_eq!(
            sig.len(),
            64,
            "ES256 requires fixed 64-byte r||s, not ASN.1 DER"
        );
        assert_eq!(hex(&sig), TEST_SIG_HEX);
        // Negative control: a constant-returning `sign_raw` would pass the
        // assertion above. Comparing a bit-flipped copy of the vector to the
        // vector would not catch that; a different message does.
        let other = signer
            .sign_raw(b"a different message")
            .expect("signing failed");
        assert_ne!(hex(&other), TEST_SIG_HEX);
    }

    #[test]
    fn jwt_signature_is_sign_raw_of_signing_input() {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};

        let signer = fixed_key_signer();
        let token = signer
            .sign_jwt_svid(
                "spiffe://example.org/workload",
                &["api.example.org"],
                serde_json::json!({"level": "asserted"}),
            )
            .unwrap();
        let (signing_input, encoded_sig) = token.rsplit_once('.').expect("compact JWS");
        let header: serde_json::Value = serde_json::from_slice(
            &URL_SAFE_NO_PAD
                .decode(signing_input.split('.').next().unwrap())
                .unwrap(),
        )
        .unwrap();
        assert_eq!(header["alg"], "ES256");
        let jwt_sig = URL_SAFE_NO_PAD.decode(encoded_sig).unwrap();
        assert_eq!(jwt_sig.len(), 64);
        // P-256 signing is RFC 6979 deterministic, and `sign_raw` is pinned to
        // an externally generated vector above, so this equality carries that
        // external oracle onto the ES256 path without a clock seam.
        assert_eq!(jwt_sig, signer.sign_raw(signing_input.as_bytes()).unwrap());
    }

    #[test]
    fn known_vector_jwks_for_fixture_key() {
        let jwks = fixed_key_signer().jwks();
        let keys = jwks["keys"].as_array().expect("jwks.keys must be an array");
        assert_eq!(keys.len(), 1, "one signing key, one published key");
        let k = &keys[0];
        assert_eq!(k["kty"], "EC");
        assert_eq!(k["crv"], "P-256");
        assert_eq!(k["alg"], "ES256");
        assert_eq!(k["use"], "sig");
        assert_eq!(k["x"], TEST_JWK_X);
        assert_eq!(k["y"], TEST_JWK_Y);
        assert_eq!(k["kid"], TEST_JWK_KID);
    }

    #[test]
    fn issued_token_header_names_the_published_key() {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};

        let signer = fixed_key_signer();
        let token = signer
            .sign_jwt_svid(
                "spiffe://example.org/workload",
                &["api.example.org"],
                serde_json::json!({}),
            )
            .unwrap();
        let header: serde_json::Value = serde_json::from_slice(
            &URL_SAFE_NO_PAD
                .decode(token.split('.').next().unwrap())
                .unwrap(),
        )
        .unwrap();
        // A consumer cannot select a key it is not told about.
        assert_eq!(header["kid"], TEST_JWK_KID);
        assert_eq!(signer.kid(), TEST_JWK_KID);
    }
}
